language: node_js
node_js:
  - 0.12
script: npm run ci
addons:
  sauce_connect:
    username: rapaz
    access_key:
      secure: Aj5yPxfY1s4PARF0i/xKLO6zxTRtz68K5NtDe6Ll3vhBi3oYesf1gRBBMrLpW1W3wNCF6EvJ2/WDK/yfG90o4VFZrtokO8ioVP4DEIWWJ1Nv5ZCyGykERcOiJ3hVqRPQuutKPLaLPvOg5WTnNxspktEeH9ZaHDzQAjmrXnJSNL5KfE0kYpUuuoyNFOHA2qyKLkVtuyRysKSF4wbOZG5cti8yce2acm7LurMnQ2DFoyxLcaRQ4PBQCSD7RYnvNwi/2hrz8lQ2cOy40LCay6wAWN6AX/ko9BIaKGVo17NMg61AohaC0Ra2gP75hwUUjGjqhkTTe7gcCmUJpm6fMN0TVjTXVjA57mm+hbN5VwzlGMbRz7GLb/lEGGG8sX/a5XIIznN6f2emeyOWE3tfDRVrCt742fijWwwU0L61Ze61TdBv7db2bkhXOcrXYrlO+/k8mA+gf15nWlsWxr7wqDE9wEYD/1uAp/nasGLKC8CLdKD1tftsMvNSFBwCvxLLvG9EqHqXZ0bGtH8GsaMYysiyfZ4kBo80rfjX8RUiZ3DCU14UpCi3ViyYTznsNUKWt1aEdCy9USuddOOK1mzA/CtbevGE6Ka3ctDtg6bpdAYDiPUl1OYG7GPaJwy9zb5Dnyko43xMpo+FCaqVBvdI4KkhUcNcsu0ez/EWkk0PAh9uCtk=
